/* tslint:disable */
/* eslint-disable */
/**
 * Name Done - First Name Service
 * An first name service API for Name Done
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface BadRequestResponseDto
 */
export interface BadRequestResponseDto {
    /**
     * HTTP status code of the error
     * @type {number}
     * @memberof BadRequestResponseDto
     */
    'statusCode': number;
    /**
     * Short descriptions of the errors
     * @type {Array<string>}
     * @memberof BadRequestResponseDto
     */
    'message': Array<string>;
    /**
     * Error type
     * @type {string}
     * @memberof BadRequestResponseDto
     */
    'error': string;
}
/**
 * 
 * @export
 * @interface NameResponseDto
 */
export interface NameResponseDto {
    /**
     * An array of possible first names
     * @type {Array<string>}
     * @memberof NameResponseDto
     */
    'names': Array<string>;
}

/**
 * EmailDomainNameApi - axios parameter creator
 * @export
 */
export const EmailDomainNameApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get a list of email domain names
         * @param {string} name Name query parameter
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        emailDomainNameControllerGet: async (name: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'name' is not null or undefined
            assertParamExists('emailDomainNameControllerGet', 'name', name)
            const localVarPath = `/name/email-domain`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (name !== undefined) {
                localVarQueryParameter['name'] = name;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * EmailDomainNameApi - functional programming interface
 * @export
 */
export const EmailDomainNameApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = EmailDomainNameApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get a list of email domain names
         * @param {string} name Name query parameter
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async emailDomainNameControllerGet(name: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<NameResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.emailDomainNameControllerGet(name, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * EmailDomainNameApi - factory interface
 * @export
 */
export const EmailDomainNameApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = EmailDomainNameApiFp(configuration)
    return {
        /**
         * 
         * @summary Get a list of email domain names
         * @param {string} name Name query parameter
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        emailDomainNameControllerGet(name: string, options?: any): AxiosPromise<NameResponseDto> {
            return localVarFp.emailDomainNameControllerGet(name, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * EmailDomainNameApi - object-oriented interface
 * @export
 * @class EmailDomainNameApi
 * @extends {BaseAPI}
 */
export class EmailDomainNameApi extends BaseAPI {
    /**
     * 
     * @summary Get a list of email domain names
     * @param {string} name Name query parameter
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EmailDomainNameApi
     */
    public emailDomainNameControllerGet(name: string, options?: AxiosRequestConfig) {
        return EmailDomainNameApiFp(this.configuration).emailDomainNameControllerGet(name, options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * FamilyNameApi - axios parameter creator
 * @export
 */
export const FamilyNameApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get a list of family names
         * @param {string} name Name query parameter
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        familyNameControllerGet: async (name: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'name' is not null or undefined
            assertParamExists('familyNameControllerGet', 'name', name)
            const localVarPath = `/name/family`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (name !== undefined) {
                localVarQueryParameter['name'] = name;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * FamilyNameApi - functional programming interface
 * @export
 */
export const FamilyNameApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = FamilyNameApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get a list of family names
         * @param {string} name Name query parameter
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async familyNameControllerGet(name: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<NameResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.familyNameControllerGet(name, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * FamilyNameApi - factory interface
 * @export
 */
export const FamilyNameApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = FamilyNameApiFp(configuration)
    return {
        /**
         * 
         * @summary Get a list of family names
         * @param {string} name Name query parameter
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        familyNameControllerGet(name: string, options?: any): AxiosPromise<NameResponseDto> {
            return localVarFp.familyNameControllerGet(name, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * FamilyNameApi - object-oriented interface
 * @export
 * @class FamilyNameApi
 * @extends {BaseAPI}
 */
export class FamilyNameApi extends BaseAPI {
    /**
     * 
     * @summary Get a list of family names
     * @param {string} name Name query parameter
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FamilyNameApi
     */
    public familyNameControllerGet(name: string, options?: AxiosRequestConfig) {
        return FamilyNameApiFp(this.configuration).familyNameControllerGet(name, options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * GivenNameApi - axios parameter creator
 * @export
 */
export const GivenNameApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get a list of given names
         * @param {string} name Name query parameter
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        givenNameControllerGet: async (name: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'name' is not null or undefined
            assertParamExists('givenNameControllerGet', 'name', name)
            const localVarPath = `/name/given`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (name !== undefined) {
                localVarQueryParameter['name'] = name;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * GivenNameApi - functional programming interface
 * @export
 */
export const GivenNameApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = GivenNameApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get a list of given names
         * @param {string} name Name query parameter
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async givenNameControllerGet(name: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<NameResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.givenNameControllerGet(name, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * GivenNameApi - factory interface
 * @export
 */
export const GivenNameApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = GivenNameApiFp(configuration)
    return {
        /**
         * 
         * @summary Get a list of given names
         * @param {string} name Name query parameter
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        givenNameControllerGet(name: string, options?: any): AxiosPromise<NameResponseDto> {
            return localVarFp.givenNameControllerGet(name, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * GivenNameApi - object-oriented interface
 * @export
 * @class GivenNameApi
 * @extends {BaseAPI}
 */
export class GivenNameApi extends BaseAPI {
    /**
     * 
     * @summary Get a list of given names
     * @param {string} name Name query parameter
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GivenNameApi
     */
    public givenNameControllerGet(name: string, options?: AxiosRequestConfig) {
        return GivenNameApiFp(this.configuration).givenNameControllerGet(name, options).then((request) => request(this.axios, this.basePath));
    }
}


